### PR TITLE
fix: rework and test `tg format`

### LINKED ISSUE #296: format fails on packages with non-module path dependencies
The CLI `format` command fails with this error on packages which import artifacts that are not modules:
```
-> Not a directory (os error 20)
-> failed to check if file exists
   internal:packages/server/src/package/format.rs:64:15 tangram_server::package::format::<impl tangram_server::Server>::format_module::{{closure}}::{{closure}}
   path = /Users/benlovy/code/packages/packages/attr/tangram.ts/patches
```

The offending import:
```
import patches from "./patches" with { type: "directory" };
```
It tried creating the invalid path `/Users/benlovy/code/packages/packages/attr/tangram.ts/patches`, which fails at the `try_exists()` call because the parent is not a directory.

### PR DESCRIPTION
**Pull request by endbr64**
The new logic simply recursively formats all modules under the argument path while accounting for `.tgignore`.

Closes #296

### CODE REVIEW

File: packages/server/src/lib.rs [hunk 1]
```diff
@@ -153,8 +153,8 @@ impl Server {
 		#[cfg(test)]
```
Comment (deciduously) [inline packages/server/src/lib.rs]: This whole block can be removed now - after some churn we now have this handled at the [bottom of this file](https://github.com/tangramdotdev/tangram/blob/2e6cdd4e7ea65f97a073dc6afecf64f83fa50501/packages/server/src/lib.rs#L1238), the value chosen is higher than the value you needed here.

Comment (endbr64) [reply packages/server/src/lib.rs]: Done, thanks!

**Comment by nitsky** [comment]
Please remove the pending snap file.
