### PR TITLE
fix: handle server stop in import/export and retry in push/pull

### LINKED ISSUE #481: Support the stop signal in import and export, make push or pull keep trying until it gets the end event

### PR DESCRIPTION
**Pull request by m-hilgendorf**
- resolves #481

### CODE REVIEW

File: packages/server/src/import.rs [hunk 1]
```diff
@@ -530,15 +530,23 @@ impl Server {
...
 			let Some(item) = tg::export::Item::from_reader(&mut reader).await? else {
 				return Ok(None);
 			};
 			Ok(Some((item, reader)))
-		})
-		.boxed();
+		});
+
+		// Stop the incoming stream when the server stops.
+		let stop = async move {
```
Comment (m-hilgendorf) [inline packages/server/src/import.rs:550]: There's an argument to be made that we should stop the _output_ stream instead of the _input_ stream, but I believe this is more correct because it allows the server to make as much progress as possible before shutting down instead of blocking until the import has completed.
